version: '3'
services:
  # Agent container
  datadog:
    build:
        context: ./
        dockerfile: Docker-dd-agent
    environment:
      - DD_API_KEY=<add key>
#      - URL=
#      - URL_PAGE_1=
#      - URL_PAGE_2=
#      - URL_PAGE_3=
#      - URL_PAGE_4=
#      - URL_5=
#      - URL_6=
#      - NAME_7=
#      - NAME_8=
#      - NAME_9=
#      - NAME_10=
#      - NAME_11=
#      - NAME_12=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/mounts:/host/proc/mounts:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  # Screenboard Creation
  screenboard_checker:
      build:
          context: ./
          dockerfile: Docker-py
      environment:
        - API_KEY=<add key>
        - APP_KEY=<add app key>
#        - IMAGE=
#        - NAME=
#        - NAME_PAGE_1=
#        - NAME_PAGE_2=
#        - NAME_PAGE_3=
#        - NAME_PAGE_4=
#        - NAME_5=
#        - NAME_6=
#        - URL=
#        - URL_PAGE_1=
#        - URL_PAGE_2=
#        - URL_PAGE_3=
#        - URL_PAGE_4=
#        - URL_5=
#        - URL_6=
      ports:
         - "10516:10516"
